# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/erikd/Dev/kage

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/erikd/Dev/kage

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/erikd/Dev/kage/CMakeFiles /home/erikd/Dev/kage//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/erikd/Dev/kage/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/erikd/Dev/kage/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kage

# Build rule for target.
kage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kage
.PHONY : kage

# fast build rule for target.
kage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/build
.PHONY : kage/fast

src/args.o: src/args.c.o
.PHONY : src/args.o

# target to build an object file
src/args.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/args.c.o
.PHONY : src/args.c.o

src/args.i: src/args.c.i
.PHONY : src/args.i

# target to preprocess a source file
src/args.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/args.c.i
.PHONY : src/args.c.i

src/args.s: src/args.c.s
.PHONY : src/args.s

# target to generate assembly for a file
src/args.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/args.c.s
.PHONY : src/args.c.s

src/ir.o: src/ir.c.o
.PHONY : src/ir.o

# target to build an object file
src/ir.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/ir.c.o
.PHONY : src/ir.c.o

src/ir.i: src/ir.c.i
.PHONY : src/ir.i

# target to preprocess a source file
src/ir.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/ir.c.i
.PHONY : src/ir.c.i

src/ir.s: src/ir.c.s
.PHONY : src/ir.s

# target to generate assembly for a file
src/ir.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/ir.c.s
.PHONY : src/ir.c.s

src/lexer.o: src/lexer.c.o
.PHONY : src/lexer.o

# target to build an object file
src/lexer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/lexer.c.o
.PHONY : src/lexer.c.o

src/lexer.i: src/lexer.c.i
.PHONY : src/lexer.i

# target to preprocess a source file
src/lexer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/lexer.c.i
.PHONY : src/lexer.c.i

src/lexer.s: src/lexer.c.s
.PHONY : src/lexer.s

# target to generate assembly for a file
src/lexer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/lexer.c.s
.PHONY : src/lexer.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/main.c.s
.PHONY : src/main.c.s

src/parser.o: src/parser.c.o
.PHONY : src/parser.o

# target to build an object file
src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/parser.c.o
.PHONY : src/parser.c.o

src/parser.i: src/parser.c.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/parser.c.i
.PHONY : src/parser.c.i

src/parser.s: src/parser.c.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/parser.c.s
.PHONY : src/parser.c.s

src/tokens.o: src/tokens.c.o
.PHONY : src/tokens.o

# target to build an object file
src/tokens.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/tokens.c.o
.PHONY : src/tokens.c.o

src/tokens.i: src/tokens.c.i
.PHONY : src/tokens.i

# target to preprocess a source file
src/tokens.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/tokens.c.i
.PHONY : src/tokens.c.i

src/tokens.s: src/tokens.c.s
.PHONY : src/tokens.s

# target to generate assembly for a file
src/tokens.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/tokens.c.s
.PHONY : src/tokens.c.s

src/vm.o: src/vm.c.o
.PHONY : src/vm.o

# target to build an object file
src/vm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/vm.c.o
.PHONY : src/vm.c.o

src/vm.i: src/vm.c.i
.PHONY : src/vm.i

# target to preprocess a source file
src/vm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/vm.c.i
.PHONY : src/vm.c.i

src/vm.s: src/vm.c.s
.PHONY : src/vm.s

# target to generate assembly for a file
src/vm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kage.dir/build.make CMakeFiles/kage.dir/src/vm.c.s
.PHONY : src/vm.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... kage"
	@echo "... src/args.o"
	@echo "... src/args.i"
	@echo "... src/args.s"
	@echo "... src/ir.o"
	@echo "... src/ir.i"
	@echo "... src/ir.s"
	@echo "... src/lexer.o"
	@echo "... src/lexer.i"
	@echo "... src/lexer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/tokens.o"
	@echo "... src/tokens.i"
	@echo "... src/tokens.s"
	@echo "... src/vm.o"
	@echo "... src/vm.i"
	@echo "... src/vm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/erikd/Dev/kage/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

